### PR TITLE
Add model for tracking subsctipion migration tasks

### PR DESCRIPTION
**Pull request by rudigiesler**
This PR adds a model and the associated migrations, list views, admin views, and tests to help track any subscription migration tasks that will be running in the background.

### CODE REVIEW

**Comment by alexmuller** [comment]
I'm not getting the `mapper` migrations to run automatically when I start the container, am I doing something wrong?

```
gates-subscription-mapper_1  | Operations to perform:
gates-subscription-mapper_1  |   Apply all migrations: admin, auth, contenttypes, sessions
gates-subscription-mapper_1  | Running migrations:
gates-subscription-mapper_1  |   No migrations to apply.
```

**Comment by rudigiesler** [comment]
@alexmuller The docker image will only be build when this branch gets merged to develop. Right now, the currently available container contains everything before this PR, so you'll only get those migrations by pulling the code and building the container yourself.

**Comment by alexmuller** [comment]
Ah sorry, I meant when I'm building the container myself locally from this branch and running it I still don't get the migrations applied. It's like Django doesn't recognise it's an app, although I see `mapper` is listed in `settings.INSTALLED_APPS`.

**Comment by rudigiesler** [comment]
@alexmuller That's strange, the image works fine on my machine.. I'm running the image with ```docker run -p 8000:8000 -e "DATABASE=postgres://postgres:@docker.for.mac.localhost/gates_subscription_mapper" -e "SUPERUSER_PASSWORD=rudipassword" local_subscription_mapper```

**Comment by alexmuller** [comment]
Sorry, my mistake! I got caught by `docker-compose` not rebuilding images automatically after code changes 😞. Will continue having a look...

**Review by alexmuller — APPROVED** [review]
This all looks good to me! I don't understand the reason for the reversal of the `created_at` index though, can you explain what that is for?

**Comment by rudigiesler** [comment]
@alexmuller Our default sorting order on that model is `-created_at`. That means that whenever we want to display or paginate that model, we'll sort and paginate by `created_at`, so it would be good to have an index on that.

The issue with a normal index is, if we're sorting and limiting by `-created_at`, but our index is in the forward direction (so oldest first), then to get the newest items we have to traverse the entire index. But by reversing the index, the newest items are on the top of the index, so getting the newest items is easier than getting the oldest ones.

**Comment by alexmuller** [comment]
Cool, thanks! 👍

**Pull request merged**
